apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-svc
  labels:
    app: k8s-demo
spec:
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 5000
  selector:
    app: k8s-demo